private["_v","_i","_p","_d","_ex","_id","_rd"];
_v=_this select 0;
_i=_this select 1;
_d=_v distance _i;
if(_d<20)exitWith{};
if((typeOf _i)in dapsExcludedAmmo)exitWith{};
sleep 0.001;
if ((_v distance _i)>_d)exitWith{};
if((getNumber(configFile>>"CfgAmmo">>typeOf _i>>"hit"))>999)exitWith{};
_p=getPosATL _i;
_id=getDir _i;
_rd=[_id,_v]call DAPS_fnc_RelDir2;
[_v,_id,_p,_i]call DAPS_fnc_React;
_ex=TRUE;
while{TRUE}do{
	if!(alive _i)exitWith{_ex=FALSE};
	if!(alive _v)exitWith{};
	_d=_v distance _i;
	if(_d>101)exitWith{_ex=FALSE};
	if(_d<30)exitWith{};
	sleep 0.001;
};
if!(alive _v)exitWith{};
if!(_ex)exitWith{};
//_p=getPosATL _i;
deleteVehicle _i;
//_p remoteExec["DAPS_fnc_Blast"];
_p call DAPS_fnc_Blast;
_a=_v getVariable"dapsAmmo";
[_v,_s,_a]call DAPS_fnc_DeductAmmo;
[_v,_s,_rd,TRUE]remoteExec["DAPS_fnc_Report"];