adminFilter[] = {"!updatezeus","kanker","cancer","n3gro","negro","kill yourself","commit suicide","n i g g a","nickga","n1gg","nigg","n3g3r","neger","niger","n1ger","n1gger","ukro","jew","j3w","negg","n3gg","fuck","bitch","b1tch","slut","retard","kys","nazi","n4z1","rape","cunt","prick","pussy","maga","queer","shit","sh!t","scrotum","whore","slut","whore","f u c k","kunt","keelyersalf"};

class arsenalConfig
{
	class west{
		riflesBlacklist[] = {"SMG_05_F","SMG_02_F","arifle_ARX_blk_F","arifle_ARX_ghex_F","arifle_ARX_hex_F","arifle_AK12U_F","arifle_AK12U_lush_F","arifle_AK12U_arid_F","arifle_Katiba_C_F","srifle_DMR_04_F","srifle_DMR_04_Tan_F","srifle_DMR_07_blk_F","srifle_DMR_07_hex_F","srifle_DMR_07_ghex_F","srifle_DMR_05_blk_F","srifle_DMR_05_hex_F","srifle_DMR_05_tan_f","srifle_DMR_01_F",	"srifle_GM6_F","srifle_GM6_camo_F","srifle_GM6_ghex_F","arifle_CTARS_blk_F","arifle_CTARS_hex_F","arifle_CTARS_ghex_F","arifle_RPK12_F","arifle_RPK12_lush_F","arifle_RPK12_arid_F","LMG_Zafir_F",	"MMG_01_hex_F","MMG_01_tan_F","MMG_01_hex_ARCO_LP_F"};
		launchersBlacklist[] = {"launch_O_Vorona_brown_F","launch_O_Vorona_green_F"};
		handgunsBlacklist[] = {"hgun_Rook40_F"};
		Uniforms[] = {"U_C_Journalist","U_B_GEN_Commander_F","U_C_Paramedic_01_F","U_O_R_Gorka_01_black_F","U_B_HeliPilotCoveralls","U_B_GhillieSuit","U_B_CombatUniform_mcam","U_B_CombatUniform_mcam_tshirt","U_B_CombatUniform_mcam_vest","U_B_Wetsuit","U_B_PilotCoveralls","U_B_SpecopsUniform_sgg","U_B_CTRG_1","U_B_CTRG_2","U_B_CTRG_3","U_B_survival_uniform","U_B_FullGhillie_lsh","U_B_FullGhillie_sard","U_B_FullGhillie_ard","U_B_T_Soldier_F","U_B_T_Soldier_AR_F","U_B_T_Soldier_SL_F","U_B_T_Sniper_F","U_B_T_FullGhillie_tna_F","U_B_CTRG_Soldier_F","U_B_CTRG_Soldier_2_F","U_B_CTRG_Soldier_3_F","U_B_CTRG_Soldier_Arid_F","U_B_CTRG_Soldier_2_Arid_F","U_B_CTRG_Soldier_3_Arid_F","U_B_CombatUniform_mcam_wdl_f","U_B_CombatUniform_tshirt_mcam_wdL_f","U_B_CombatUniform_vest_mcam_wdl_f"};
		Vests[] = {"V_TacVest_gen_F","V_Press_F","V_Chestrig_khk","V_Chestrig_rgr","V_Chestrig_blk","V_Chestrig_oli","V_TacVest_khk","V_TacVest_brn","V_TacVest_oli","V_TacVest_blk","V_TacChestrig_grn_F","V_TacChestrig_oli_F","V_TacChestrig_cbr_F","V_PlateCarrier1_rgr_noflag_F","V_PlateCarrier2_rgr_noflag_F","V_LegStrapBag_black_F","V_LegStrapBag_coyote_F","V_LegStrapBag_olive_F","V_CarrierRigKBT_01_EAF_F","V_CarrierRigKBT_01_light_EAF_F","V_BandollierB_oli","V_BandollierB_blk","V_BandollierB_rgr","V_BandollierB_cbr","V_BandollierB_khk","V_TacVest_camo","V_TacVestIR_blk","V_I_G_resistanceLeader_F","V_Rangemaster_belt","V_PlateCarrierGL_rgr","V_PlateCarrierGL_mtp","V_PlateCarrierSpec_rgr","V_PlateCarrierSpec_blk","V_PlateCarrierSpec_mtp","V_RebreatherB","V_PlateCarrierL_CTRG","V_PlateCarrierH_CTRG","V_PlateCarrier_Kerry","V_PlateCarrierSpec_tna_F","V_PlateCarrierGL_tna_F","V_PlateCarrier1_wdl","V_PlateCarrier2_wdl","V_PlateCarrierGL_wdl","V_PlateCarrierSpec_wdl","V_PlateCarrier1_blk","V_PlateCarrier2_blk","V_PlateCarrierGL_blk"};	
		Backpacks[] = {"B_Messenger_Gray_F","B_Bergen_tna_F","B_Carryall_oli","B_Carryall_blk","B_FieldPack_green_F","B_FieldPack_oli","B_Bergen_mcamo_F","B_AssaultPack_rgr","B_AssaultPack_sgg","B_AssaultPack_blk","B_AssaultPack_khk","B_AssaultPack_cbr","B_AssaultPack_mcamo","B_Kitbag_rgr","B_Kitbag_mcamo","B_Kitbag_sgg","B_Kitbag_cbr","B_Kitbag_tan","B_TacticalPack_rgr","B_TacticalPack_mcamo","B_TacticalPack_blk","B_TacticalPack_oli","B_FieldPack_khk","B_FieldPack_cbr","B_FieldPack_blk","B_Carryall_mcamo","B_Carryall_khk","B_Carryall_cbr","B_Bergen_mcamo","B_AssaultPack_tna_F","B_ViperHarness_blk_F","B_ViperLightHarness_blk_F","B_ViperLightHarness_oli_F","B_ViperHarness_oli_F","B_ViperHarness_khk_F","B_ViperLightHarness_khk_F","B_Messenger_Coyote_F","B_Messenger_Olive_F","B_Messenger_Black_F","B_LegStrapBag_black_F","B_LegStrapBag_coyote_F","B_LegStrapBag_olive_F","B_RadioBag_01_wdl_F","B_RadioBag_01_mtp_F","B_RadioBag_01_tropic_F","B_RadioBag_01_black_F","B_Carryall_green_F","B_Carryall_wdl_F","B_Carryall_eaf_F","B_AssaultPack_wdl_F","B_AssaultPack_eaf_F","B_Static_Designator_01_weapon_F"};
		Helmets[] = {"H_PASGT_basic_blue_press_F","H_Cap_red","H_Cap_police","H_Booniehat_khk_hs","H_Booniehat_oli","H_Booniehat_tna_F","H_Cap_usblack","H_MilCap_mcamo","H_MilCap_tna_F","H_MilCap_wdl","H_HelmetB_light_black","H_HelmetB_light_desert","H_HelmetB_light_grass","H_HelmetB_light_sand","H_HelmetB_light_snakeskin","H_Cap_khaki_specops_UK","H_HelmetB_camo","H_HelmetB","H_HelmetB_paint","H_Booniehat_mcamo","H_Booniehat_grn","H_Booniehat_tan","H_HelmetB_plain_blk","H_HelmetSpecB","H_HelmetSpecB_paint1","H_HelmetSpecB_paint2","H_HelmetSpecB_blk","H_HelmetSpecB_snakeskin","H_HelmetSpecB_sand","H_Cap_tan_specops_US","H_HelmetCrew_B","H_PilotHelmetFighter_B","H_PilotHelmetHeli_B","H_CrewHelmetHeli_B","H_Beret_02","H_HelmetB_TI_tna_F","H_HelmetB_TI_arid_F","H_HelmetB_Enh_tna_F","H_HelmetB_Light_tna_F","H_HelmetHBK_chops_F","H_HelmetHBK_ear_F","H_HelmetHBK_headset_F","H_HelmetHBK_F","H_Booniehat_wdl","H_HelmetB_plain_wdl","H_HelmetB_light_wdl","H_HelmetSpecB_wdl","H_HelmetB","H_HelmetB_plain_blk","H_HelmetB_plain_wdl","H_HelmetB_camo","H_HelmetB_paint","H_HelmetB_snakeskin","H_HelmetB_tna_F","H_HelmetB_grass","H_HelmetB_desert"};	
		Terminals[] = {"B_UavTerminal","ItemGPS"};
	};
	class east{
		riflesBlacklist[] = {"SMG_01_F","arifle_Mk20_F","arifle_Mk20_plain_F","arifle_Mk20_GL_F","arifle_Mk20_GL_plain_F","arifle_Mk20_MRCO_plain_F","arifle_Mk20_MRCO_pointer_F","arifle_Mk20_GL_MRCO_pointer_F","arifle_MX_F","arifle_MX_GL_F","arifle_MX_Black_F","arifle_MX_GL_Black_F","arifle_MX_khk_F","arifle_MX_GL_khk_F","arifle_SPAR_01_blk_F","arifle_SPAR_01_khk_F","arifle_SPAR_01_snd_F","arifle_SPAR_01_GL_blk_F","arifle_SPAR_01_GL_khk_F","arifle_SPAR_01_GL_snd_F","arifle_TRG21_F","arifle_TRG21_GL_F","arifle_Mk20C_F","arifle_Mk20C_plain_F","arifle_MXC_F","arifle_MXC_khk_F","arifle_MXC_Black_Holo_Pointer_F","arifle_TRG20_F","srifle_DMR_02_F","srifle_DMR_02_camo_F","srifle_DMR_02_sniper_F","srifle_DMR_03_F","srifle_DMR_03_khaki_F","srifle_DMR_03_tan_F","srifle_DMR_03_multicam_F","srifle_DMR_03_woodland_F","srifle_DMR_06_camo_F","srifle_DMR_06_olive_F","srifle_DMR_06_camo_khs_F","srifle_EBR_F","arifle_MXM_F","arifle_MXM_Black_F","arifle_MXM_khk_F","arifle_SPAR_03_blk_F","arifle_SPAR_03_khk_F","arifle_SPAR_03_snd_F","srifle_LRR_F","srifle_LRR_camo_F","srifle_LRR_tna_F","LMG_Mk200_F","LMG_Mk200_black_F","arifle_MX_SW_F","arifle_MX_SW_Black_F","arifle_MX_SW_khk_F","arifle_MX_SW_Black_Pointer_F","arifle_SPAR_02_blk_F","arifle_SPAR_02_khk_F","arifle_SPAR_02_snd_F","MMG_02_camo_F","MMG_02_black_F","MMG_02_sand_F"};
		launchersBlacklist[] = {"launch_MRAWS_olive_F","launch_MRAWS_olive_rail_F","launch_MRAWS_green_F","launch_MRAWS_green_rail_F","launch_MRAWS_sand_F","launch_MRAWS_sand_rail_F","launch_NLAW_F"};
		handgunsBlacklist[] = {"hgun_Pistol_heavy_01_F","hgun_Pistol_heavy_01_green_F","hgun_ACPC2_F"};
		Uniforms[] = {"U_C_Journalist","U_B_GEN_Commander_F","U_C_Paramedic_01_F","U_O_SpecopsUniform_ocamo","U_O_SpecopsUniform_blk","U_O_OfficerUniform_ocamo","U_O_Wetsuit","U_O_GhillieSuit","U_O_FullGhillie_lsh","U_O_FullGhillie_sard","U_O_FullGhillie_ard","U_O_officer_noInsignia_hex_F","U_O_V_Soldier_Viper_hex_F","U_O_V_Soldier_Viper_F","U_O_T_FullGhillie_tna_F","U_O_T_Soldier_F","U_O_T_Officer_F","U_O_T_Sniper_F","U_O_CombatUniform_oucamo","U_O_PilotCoveralls","U_O_R_Gorka_01_F","U_O_R_Gorka_01_brown_F","U_O_R_Gorka_01_camo_F","U_O_R_Gorka_01_black_F"};
		Vests[] = {"V_TacVest_gen_F","V_Press_F","V_CarrierRigKBT_01_Olive_F","V_CarrierRigKBT_01_light_Olive_F","V_CarrierRigKBT_01_heavy_Olive_F","V_Chestrig_khk","V_Chestrig_rgr","V_Chestrig_blk","V_Chestrig_oli","V_TacVest_khk","V_TacVest_brn","V_TacVest_oli","V_TacVest_blk","V_HarnessO_brn","V_HarnessOGL_brn","V_HarnessO_gry","V_HarnessOGL_gry","V_HarnessOSpec_brn","V_HarnessOSpec_gry","V_RebreatherIR","V_TacChestrig_grn_F","V_TacChestrig_oli_F","V_TacChestrig_cbr_F","V_HarnessO_ghex_F","V_HarnessOGL_ghex_F","V_BandollierB_ghex_F","V_PlateCarrier1_rgr_noflag_F","V_PlateCarrier2_rgr_noflag_F","V_LegStrapBag_black_F","V_LegStrapBag_coyote_F","V_LegStrapBag_olive_F","V_CarrierRigKBT_01_EAF_F","V_CarrierRigKBT_01_light_EAF_F","V_SmershVest_01_F","V_SmershVest_01_radio_F","V_BandollierB_oli","V_BandollierB_blk","V_BandollierB_rgr","V_BandollierB_cbr","V_BandollierB_khk","V_TacVest_camo","V_TacVestIR_blk","V_I_G_resistanceLeader_F","V_Rangemaster_belt","V_PlateCarrier2_blk","V_PlateCarrier1_blk"};
		Backpacks[] = {"B_Bergen_hex_F","B_AssaultPack_wdl_F","B_AssaultPack_ocamo","B_Kitbag_cbr","B_TacticalPack_ocamo","B_TacticalPack_blk","B_FieldPack_ocamo","B_FieldPack_oucamo","B_Carryall_ocamo","B_Carryall_oucamo","B_AssaultPack_blk","B_AssaultPack_cbr","B_AssaultPack_sgg","B_AssaultPack_rgr","B_AssaultPack_khk","B_Kitbag_tan","B_Bergen_rgr","B_ViperHarness_blk_F","B_ViperHarness_ghex_F","B_ViperHarness_hex_F","B_ViperHarness_khk_F","B_ViperHarness_oli_F","B_ViperLightHarness_blk_F","B_ViperLightHarness_ghex_F","B_ViperLightHarness_hex_F","B_ViperLightHarness_khk_F","B_ViperLightHarness_oli_F","B_LegStrapBag_black_F","B_LegStrapBag_coyote_F","B_LegStrapBag_olive_F","B_Messenger_Coyote_F","B_Messenger_Olive_F","B_Messenger_Black_F","B_Messenger_Gray_F","B_RadioBag_01_black_F","B_RadioBag_01_ghex_F","B_RadioBag_01_hex_F","B_RadioBag_01_oucamo_F","O_Static_Designator_02_weapon_F","B_FieldPack_blk","B_FieldPack_ghex_F","B_Carryall_ghex_OTExp_F","B_Carryall_blk","B_Carryall_taiga_F","B_FieldPack_taiga_F","B_FieldPack_oli","B_FieldPack_khk","B_FieldPack_green_RPG_AT_F"};
		Helmets[] = {"H_PASGT_basic_blue_press_F","H_Cap_red","H_Cap_police","H_Cap_brn_SPECOPS","H_HelmetCrew_O","H_PilotHelmetFighter_O","H_PilotHelmetHeli_O","H_CrewHelmetHeli_O","H_HelmetO_ocamo","H_HelmetLeaderO_ocamo","H_MilCap_ocamo","H_HelmetO_oucamo","H_HelmetLeaderO_oucamo","H_HelmetSpecO_ocamo","H_HelmetSpecO_blk","H_Beret_ocamo","H_HelmetO_ViperSP_hex_F","H_HelmetO_ViperSP_ghex_F","H_HelmetSpecO_ghex_F","H_HelmetLeaderO_ghex_F","H_HelmetO_ghex_F","H_HelmetCrew_O_ghex_F","H_MilCap_ghex_F","H_Tank_black_F","H_Beret_CSAT_01_F","H_HelmetAggressor_F","H_HelmetAggressor_cover_F","H_HelmetAggressor_cover_taiga_F","H_Beret_blk","H_Booniehat_taiga","H_Booniehat_khk" , "H_Cap_brn_SPECOPS","H_MilCap_taiga"};
		Terminals[] = {"O_UavTerminal","ItemGPS"};
	};
};

class logisticsConfig
{
	class cargoTypes
	{
		Cargo[] = {"B_Slingload_01_Medevac_F","Box_CSAT_Equip_F","Box_CSAT_Uniforms_F","Box_NATO_Uniforms_F","Box_NATO_Equip_F","B_Slingload_01_Fuel_F","B_Slingload_01_Repair_F","B_Slingload_01_Ammo_F","Land_Pod_Heli_Transport_04_repair_F","Land_Pod_Heli_Transport_04_fuel_F","Land_Pod_Heli_Transport_04_ammo_F","Box_East_AmmoVeh_F","Box_NATO_AmmoVeh_F","Box_NATO_Ammo_F","Box_NATO_Grenades_F","Box_NATO_Wps_F","Box_NATO_AmmoOrd_F","Box_NATO_WpsLaunch_F","Box_NATO_WpsSpecial_F","B_supplyCrate_F","Box_East_Ammo_F","Box_East_Grenades_F","Box_East_Wps_F","Box_East_AmmoOrd_F","Box_East_WpsLaunch_F","Box_East_WpsSpecial_F","O_supplyCrate_F"};
	};
};