class CfgWLRequisitionPresets
{
	class A3ReduxAll
	{
		class WEST
		{
			class Infantry
			{
				class CUP_B_USMC_Soldier					{cost = 20;		requirements[]={};	};	// "Rifleman"
				class CUP_B_BAF_Soldier_Paratrooper_DPM		{cost = 25;		requirements[]={};	};	// "Para Trooper"
				class CUP_B_USMC_Crew						{cost = 15;		requirements[]={};	};	// "Crewman"
				class CUP_B_USMC_Pilot 						{cost = 10;		requirements[]={};	};	// "Pilot"
				class CUP_B_USMC_Soldier_GL					{cost = 50;		requirements[]={};	};	// "Grenadier"
				class CUP_B_USMC_Medic						{cost = 20;		requirements[]={};	};	// "Combat Life Saver"
				class CUP_B_USMC_Soldier_AR					{cost = 50;		requirements[]={};	};	// "Autorifleman"
				class CUP_B_USMC_SpecOps_SD					{cost = 25;		requirements[]={};	};	// "Shotgun"
				class CUP_B_USMC_Soldier_Marksman			{cost = 60;		requirements[]={};	};	// "Marksman"
				class CUP_B_USMC_Engineer					{cost = 100;	requirements[]={};	};	// "Repair Specialist"
				class CUP_B_USMC_Soldier_MG					{cost = 80;		requirements[]={};	};	// "Heavy Gunner"
				class CUP_B_USMC_Soldier_AT					{cost = 100;	requirements[]={};	};	// "Rifleman (AT)"
				class CUP_B_USMC_Soldier_HAT				{cost = 150;	requirements[]={};	};	// "Missile Specialist (AT)"
				class CUP_B_USMC_Soldier_AA					{cost = 150;	requirements[]={};	};	// "Missile Specialist (AA)"
				class CUP_B_USMC_Sniper_M40A3				{cost = 80;		requirements[]={};	};	// "Sharpshooter"
				class CUP_B_USMC_Sniper_M107				{cost = 100;	requirements[]={};	};	// "Sniper"
				
			};
			class Vehicles
			{
				class CUP_B_M1030_USMC						{cost =  10;	requirements[]={};	};	// "Bike"
				class B_Quadbike_01_F						{cost =  20;	requirements[]={};	};	// "Quad Bike"
				class CUP_B_M1152_USMC			 			{cost = 100;	requirements[]={};	};	// "Unarmed Humvee Pickup"
				class CUP_B_nM1025_Unarmed_USMC_WDL			{cost = 150;	requirements[]={};	};	// "Unarmed HUMVEE"								
				class CUP_B_MTVR_USMC		 				{cost = 200;	requirements[]={};	};	// "MTVR Transport"
				class CUP_B_MTVR_ReFuel_USMC				{cost = 500;	requirements[]={};	};	// "MTVR Fuel"
				class CUP_B_nM997_USMC_WDL					{cost = 350;	requirements[]={};	};	// "Humvee Medical"
				class CUP_B_nM1025_SOV_M2_USMC_WDL			{cost = 200;	requirements[]={};	};	// "Opentop HUMVEE w/.50"
				class CUP_B_nM1025_SOV_MK19_USMC_WDL		{cost = 250;	requirements[]={};	};	// "Opentop HUMVEE GMG"
				class CUP_B_M1151_M2_USMC					{cost = 500;	requirements[]={};	};	// "Humvee HMG"
				class CUP_B_M1165_GMV_USMC					{cost = 600;	requirements[]={};	};	// "Humvee Minigun"
				class CUP_B_M1151_Mk19_USMC					{cost = 700;	requirements[]={};	};	// "Humvee GMG"
				class CUP_B_nM1036_TOW_DF_USMC_WDL			{cost = 1200;	requirements[]={};	};	// "Humvee TOW"
				class CUP_B_nM1097_AVENGER_USA_WDL			{cost = 3000;	requirements[]={};	};	// "Humvee Avenger AA"
				class CUP_B_MTVR_Repair_USMC				{cost = 2000;	requirements[]={};	};	// "MTVR Repair"
				class CUP_B_MTVR_Ammo_USMC					{cost = 3000;	requirements[]={};	};	// "HEMTT Ammo"
				
				
				//class CUP_B_M1126_ICV_M2_Woodland			{cost = 2000;	requirements[]={};	};	// "Striker M2"
				//class CUP_B_M1126_ICV_MK19_Woodland			{cost = 2200;	requirements[]={};	};	// "Striker MK19"
				//class CUP_B_M1128_MGS_Woodland				{cost = 2500;	requirements[]={};	};	// "Striker MGS"
				class CUP_B_M113A3_USA						{cost = 1200;	requirements[]={};	};	// "APC w/.50"
				class CUP_B_M163_Vulcan_USA					{cost = 2000;	requirements[]={};	};	// "APC w/gatlin gun"
				class CUP_B_AAV_USMC						{cost = 2000;	requirements[]={};	};	// "Marine APC"
				class CUP_B_LAV25M240_USMC					{cost = 3000;	requirements[]={};	};	// "LAV25"
				class CUP_B_M2Bradley_USA_W					{cost = 5000;	requirements[]={};	};	// "Bradley IFV"
				class CUP_B_M6LineBacker_USA_W				{cost = 6000;	requirements[]={};	};	// "Bradley IFV AA"
				class CUP_B_M60A3_TTS_USMC					{cost = 6000;	requirements[]={};	};	// "M60 Patton"
				class CUP_B_M1A1FEP_Woodland_USMC			{cost = 12000;	requirements[]={};	};	// "Abrams"
				class CUP_B_Challenger2_2CW_BAF				{cost = 12000;	requirements[]={};	};	// "Challenger 2"
				class CUP_B_Leopard2A6_HIL					{cost = 12000;	requirements[]={};	};	// "Leopard2"
				class CUP_B_M270_DPICM_USMC					{cost = 20000;	requirements[]={};	};	// "M270 Artillery" 
				 
				 
			};
			class Aircraft
			{
				class CUP_B_MH6J_USA						{cost = 500;	requirements[]={"H"};	};	// "Littlebird"
				class CUP_B_AH6J_USA						{cost = 5000;	requirements[]={"H"};	};	// "Littlebird Armed"
				class CUP_B_UH60M_US						{cost = 1000;	requirements[]={"H"};	};	// "Blackhawk Armed"
				class CUP_B_CH47F_USA						{cost = 1500;	requirements[]={"H"};	};	// "CH-47F Chinook"
				class CUP_B_C130J_GB						{cost = 2000;	requirements[]={"A"};	};	// "C130 Transport";
				class CUP_B_UH1Y_Gunship_Dynamic_USMC		{cost = 6000;	requirements[]={"H"};	};	// "Venom Gunship"
				class CUP_B_MH60L_DAP_4x_US					{cost = 8000;	requirements[]={"H"};	};	// "Blackhawk Rockets"
				class CUP_B_AH1Z_Dynamic_USMC				{cost = 12000;	requirements[]={"H"};	};	// "AH1Z Cobra"
				class CUP_B_AH64D_DL_USA					{cost = 15000;	requirements[]={"H"};	};	// "AH64D Apache"				
				class CUP_B_A10_DYN_USA						{cost = 18000;	requirements[]={"A"};	};	// "A-10 Warthog"
				class CUP_B_JAS39_HIL						{cost = 20000;	requirements[]={"A"};	};	// "JAS39 GRIPEN"
				class CUP_B_AV8B_DYN_USMC					{cost = 25000;	requirements[]={"A"};	};	// "Sea Harrier";
				
				
			};
			class Naval
			{
				class CUP_B_RHIB_USMC						{cost = 100;	requirements[]={"W"};	};	// "RHIB"
				class CUP_B_LCU1600_USMC					{cost = 2000;	requirements[]={"W"};	};	// "Large Boat"
				
			};
			class Gear
			{
				class CUP_BOX_USMC_Uniforms_F				{cost = 100;	requirements[]={};	};	// "Uniforms Box "
				class CUP_BOX_USMC_Ammo_F					{cost = 200;	requirements[]={};	};	// "Basic Ammo "
				class CUP_BOX_USMC_Grenades_F				{cost = 200;	requirements[]={};	};	// "Grenades"
				class CUP_BOX_USMC_Wps_F					{cost = 250;	requirements[]={};	};	// "Basic Weapons "
				class CUP_BOX_USMC_AmmoOrd_F				{cost = 750;	requirements[]={};	};	// "Explosives "
				class CUP_BOX_USMC_WpsLaunch_F				{cost = 300;	requirements[]={};	};	// "Launchers "
				class CUP_BOX_USMC_Support_F				{cost = 400;	requirements[]={};	};	// "Support"
				class CUP_BOX_USMC_WpsSpecial_F				{cost = 600;	requirements[]={};	};	// "Support"
				class CUP_VABox_USMC						{cost = 2000;	requirements[]={};	};	// "Arsenal"
				class CUP_BOX_USMC_AmmoVeh_F				{cost = 500;	requirements[]={};	};	// "Vehicle Ammo"					
			};
			class Defences
			{
				class CUP_B_SearchLight_static_USMC			{cost = 50;	requirements[]={};	};		// "Search Light"
				class CUP_B_M2StaticMG_MiniTripod_USMC		{cost = 300;	requirements[]={};	};	// "M2 .50 Low"
				class CUP_B_M2StaticMG_USMC					{cost = 300;	requirements[]={};	};	// "M2 .50 Raised"
				class CUP_B_MK19_TriPod_USMC				{cost = 450;	requirements[]={};	};	// "MK19 Low"
				class CUP_B_Stinger_AA_pod_Base_USMC		{cost = 600;	requirements[]={};	};	// "Static Stinger (AA) "
				class CUP_B_TOW_TriPod_USMC					{cost = 600;	requirements[]={};	};	// "Static TOW (AT) "
				//class B_SAM_System_03_F						{cost = 8000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "MIM-145 Defender"
				//class B_Radar_System_01_F					{cost = 5000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "AN/MPQ-105 Radar"
				class CUP_B_M252_USMC						{cost = 10000;	requirements[]={};	};	// "Mortar"
				class CUP_B_M119_USMC						{cost = 20000;	requirements[]={};	};	// "Cannon Artillery" 
				//class B_UGV_02_Demining_F					{cost = 1500;	requirements[]={};	};	// "UGAS demining"
				//class B_UAV_05_F 							{cost = 25000;	requirements[]={"A"};	};	// "UCAV";
				//class B_UAV_02_F 							{cost = 25000;	requirements[]={"A"};	};	// "greyhawk AT";
				//class B_UAV_02_CAS_F						{cost = 25000;	requirements[]={"A"};	};	// "greyhawk LGB";
				//class B_T_UAV_03_F 						{cost = 25000;	requirements[]={"A"};	};	// "Firescout";
				//class B_UAV_01_F 							{cost = 500;	requirements[]={};	};	// "AR-2 Darter";
				//class B_UAV_06_F							{cost = 500;	requirements[]={};	};	// "AL-6 Pelican";
				//class B_UAV_06_medical_F					{cost = 500;	requirements[]={};	};	// "AL-6 Pelican medical";
				//class B_AAA_System_01_F 					{cost = 8000;	requirements[]={};	};	// "Phalax";

			};
		};
		class EAST
		{
			class Infantry
			{
				class CUP_O_RU_Soldier_EMR					{cost = 20;	requirements[]={};	};	// "Rifleman"
				//class 										{cost = 25;	requirements[]={};	};	// "Para Trooper"
				class CUP_O_RUS_SpecOps_SD_Autumn			{cost = 40;		requirements[]={};	};	// "Spetsnaz Operator"
				class CUP_O_RU_Crew							{cost = 15;		requirements[]={};	};	// "Crewman"
				class CUP_O_RU_Pilot						{cost = 10;		requirements[]={};	};	// "Pilot"
				class CUP_O_RU_Soldier_GL					{cost = 50;		requirements[]={};	};	// "Grenadier"
				class CUP_O_RU_Medic						{cost = 20;		requirements[]={};	};	// "Medic"
				class CUP_O_RU_Soldier_AR					{cost = 50;		requirements[]={};	};	// "Autorifleman"
				class CUP_O_RU_Sniper						{cost = 60;		requirements[]={};	};	// "Marksman"
				class CUP_O_RU_Engineer						{cost = 100;	requirements[]={};	};	// "Repair Specialist"
				class CUP_O_RU_Soldier_MG					{cost = 80;		requirements[]={};	};	// "Heavy Gunner"
				class CUP_O_RU_Soldier_LAT					{cost = 100;	requirements[]={};	};	// "Rifleman (LAT)"
				class CUP_O_RU_Soldier_AT					{cost = 150;	requirements[]={};	};	// "Rifleman (AT RPG7)"
				class CUP_O_RU_Soldier_HAT					{cost = 250;	requirements[]={};	};	// "Heavy AT"
				class CUP_O_RU_Soldier_AA					{cost = 150;	requirements[]={};	};	// "Missile Specialist (AA)"
				class CUP_O_RU_Spotter						{cost = 80;		requirements[]={};	};	// "Sharpshooter"
				class CUP_O_RU_Sniper_KSVK					{cost = 100;	requirements[]={};	};	// "Sniper KSVK"

			};
			class Vehicles
			{
				class CUP_O_UAZ_Open_RU						{cost = 20;		requirements[]={};	};	// "UAZ Open Top"
				class CUP_O_GAZ_Vodnik_Unarmed_RU			{cost = 100;	requirements[]={};	};	// "Vodnik (Unarmed)"
				class CUP_O_UAZ_MG_RU						{cost = 300;	requirements[]={};	};	// "UAZ MG"
				class CUP_O_Ural_RU							{cost = 200;	requirements[]={};	};	// "Ural Transport"
				class CUP_O_Ural_Refuel_RU					{cost = 500;	requirements[]={};	};	// "Ural Fuel"
				class CUP_O_GAZ_Vodnik_MedEvac_RU			{cost = 350;	requirements[]={};	};	// "Vodnik Medical"
				class CUP_O_GAZ_Vodnik_AGS_RU				{cost = 350;	requirements[]={};	};	// "Vodnik GMG"
				class CUP_O_UAZ_SPG9_RU						{cost = 400;	requirements[]={};	};	// "UAZ (LAT)"
				class CUP_O_UAZ_METIS_RU					{cost = 1000;	requirements[]={};	};	// "UAZ (HAT)"
				class CUP_O_Ural_Repair_RU					{cost = 2000;	requirements[]={};	};	// "Ural Repair"
				class CUP_O_Ural_Reammo_RU					{cost = 3000;	requirements[]={};	};	// "Ural Ammo"
				class CUP_O_GAZ_Vodnik_KPVT_RU				{cost = 1000;	requirements[]={};	};	// "Vodnik HMG"
				class CUP_O_GAZ_Vodnik_BPPU_RU				{cost = 1500;	requirements[]={};	};	// "Vodnik GMG Cannon"
				class CUP_O_BTR60_RU						{cost = 2000;	requirements[]={};	};	// "BTR60"
				class CUP_O_BRDM2_ATGM_RUS					{cost = 2500;	requirements[]={};	};	// "BRDM-2 ATGM"
				class CUP_O_BTR80_CAMO_RU					{cost = 3000;	requirements[]={};	};	// "BTR80"
				class CUP_O_BTR80A_CAMO_RU					{cost = 4000;	requirements[]={};	};	// "BTR80a"
				class CUP_O_BMP2_RU							{cost = 5000;	requirements[]={};	};	// "BMP-2"
				class CUP_O_Ural_ZU23_RU					{cost = 2000;	requirements[]={};	};	// "Ural AA"
				class CUP_O_ZSU23_ChDKZ						{cost = 4500;	requirements[]={};	};	// "APC AA"
				class CUP_O_2S6_RU							{cost = 12000;	requirements[]={};	};	// "Tunguska"
				class CUP_O_T34_TKA							{cost = 4000;	requirements[]={};	};	// "T-34"
				class CUP_O_T55_CHDKZ						{cost = 6000;	requirements[]={};	};	// "T-55"
				class CUP_O_T72_RU							{cost = 9500;	requirements[]={};	};	// "T-72"

				class CUP_O_BM21_RU							{cost = 20000;	requirements[]={};	};	// "Grad Artillery"
				

			};
			class Aircraft
			{
				class CUP_O_Mi8AMT_RU						{cost = 700;	requirements[]={"H"};	};	// "MI-8 (Unarmed)"
				class CUP_O_Mi8_medevac_RU			 		{cost = 1000;	requirements[]={"H"};	};	// "Mi-8 (Medical)"
				class CUP_O_MI6A_RU							{cost = 1800;	requirements[]={"H"};	};	// "Mi-6A Hook"
				class CUP_O_Mi8_RU							{cost = 9000;	requirements[]={"H"};	};	// "Mi-8 Rockets"	
				class CUP_O_Mi24_V_Dynamic_RU				{cost = 12000;	requirements[]={"H"};	};	// "Mi-24 Dynamic"				
				class CUP_O_Ka50_DL_RU						{cost = 15000;	requirements[]={"H"};	};	// "KA-50"
				class CUP_O_L39_TK							{cost = 14000;	requirements[]={"A"};	};	// "L-39zA"
				class CUP_O_Su25_Dyn_RU						{cost = 18000;	requirements[]={"A"};	};	// "SU25 Frogfoot (CAS)"
				class CUP_O_SU34_RU							{cost = 30000;	requirements[]={"A"};	};	// "SU-34"
				
				
			};
			class Naval
			{
				class CUP_O_PBX_RU							{cost = 50;		requirements[]={"W"};	};	// "Boat"
				class CUP_O_ZUBR_RU							{cost = 40000;	requirements[]={"W"};	};	// "ZUBR Class LCAC"
				
			};
			class Gear
			{
				class CUP_BOX_RU_Uniforms_F					{cost = 100;	requirements[]={};	};	// "Uniforms [CSAT]"
				class CUP_BOX_RU_Ammo_F						{cost = 200;	requirements[]={};	};	// "Basic Ammo [CSAT]"
				class CUP_BOX_RU_Grenades_F					{cost = 200;	requirements[]={};	};	// "Grenades [CSAT]"
				class CUP_BOX_RU_Wps_F						{cost = 250;	requirements[]={};	};	// "Basic Weapons [CSAT]"
				class CUP_BOX_RU_AmmoOrd_F					{cost = 750;	requirements[]={};	};	// "Explosives [CSAT]"
				class CUP_BOX_RU_WpsLaunch_F				{cost = 300;	requirements[]={};	};	// "Launchers [CSAT]"
				class CUP_BOX_RU_WpsSpecial_F				{cost = 600;	requirements[]={};	};	// "Special Weapons [CSAT]"
				class CUP_BOX_RU_Support_F					{cost = 500;	requirements[]={};	};	// "Supply Box [CSAT]"
				class CUP_VABox_RU							{cost = 2000;	requirements[]={};	};	// "Arsenal"
				class CUP_BOX_RU_AmmoVeh_F					{cost = 500;	requirements[]={};	};	// "Vehicle Ammo [CSAT]"

			};
			class Defences
			{
				class CUP_O_SearchLight_static_RU			{cost = 50;	requirements[]={};		};	// "SearchLight"
				class CUP_O_KORD_high_RU					{cost = 300;	requirements[]={};	};	// "KORD HMG .50"
				class CUP_O_AGS_RU							{cost = 450;	requirements[]={};	};	// "MG 20 mm"
				class CUP_O_ZU23_RU							{cost = 600;	requirements[]={};	};	// "Static Cannon AA Launcher"
				class CUP_O_Igla_AA_pod_RU_M_BeigeDigital	{cost = 600;	requirements[]={};	};	// "Static Launcher (AA)"
				class CUP_O_Metis_RU						{cost = 600;	requirements[]={};	};	// "Static Metis Launcher (AT) LOW"
				class CUP_O_Kornet_RU						{cost = 600;	requirements[]={};	};	// "Static Kornet Launcher (AT) High"
				//class O_SAM_System_04_F						{cost = 8000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "S-750 Rhea"
				//class O_Radar_System_02_F					{cost = 5000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "R-750 Cronus Radar"
				class CUP_O_2b14_82mm_RU					{cost = 10000;	requirements[]={};	};	// "Mortar"
				class CUP_O_D30_RU		 					{cost = 20000;	requirements[]={};	};	// "Heavy Artillery";

			};
		};
	};
};