// Vehicles that use each type of APS
dapsLight=["O_MRAP_02_F","O_MRAP_02_gmg_F","O_MRAP_02_hmg_F","O_T_MRAP_02_F","O_T_MRAP_02_gmg_F","O_T_MRAP_02_hmg_F"];
dapsMedium=["O_APC_Tracked_02_cannon_F","O_APC_Wheeled_02_rcws_v2_F","O_T_APC_Tracked_02_cannon_ghex_F","O_T_APC_Wheeled_02_rcws_v2_ghex_F",
"O_SFIA_APC_Tracked_02_cannon_lxWS",
"VME_PLA_ZTZ99A","VME_PLA_ZTZ99","VME_PLA_ZTZ99_DES","VME_PLA_ZTZ99A_DES",
"O_ZTZ99A","O_ZTZ96B","O_ZTQ15","O_ZBD04A","O_ZBL09","O_ZTL11",
"Sparky_Japan_2035_Rhino_JGSDF","Sparky_Japan_2035_Marshall_JGSDF"
];
dapsHeavy=[];
dapsTrophyLV=["B_MRAP_01_gmg_F","B_MRAP_01_hmg_F","B_T_MRAP_01_F","B_T_MRAP_01_gmg_F","B_T_MRAP_01_hmg_F",
"I_MRAP_03_F","I_MRAP_03_gmg_F","I_MRAP_03_hmg_F",
"B_D_MRAP_01_hmg_lxWS",
"B_D_MRAP_01_lxWS",
"B_D_MRAP_01_hmg_lxWS",
"B_UN_MRAP_01_lxWS"
];
dapsTrophyMV=[
"B_APC_Wheeled_01_cannon_F","B_T_APC_Wheeled_01_cannon_F", "B_APC_Wheeled_03_cannon_F", "I_Truck_02_MRL_F", "B_MBT_01_mlrs_F",
"B_AFV_Wheeled_01_cannon_F","B_AFV_Wheeled_01_up_cannon_F","B_T_AFV_Wheeled_01_cannon_F","B_T_AFV_Wheeled_01_up_cannon_F",
"I_APC_Wheeled_03_cannon_F","I_APC_tracked_03_cannon_F",
"I_APC_Wheeled_03_Cannon_LDF_F","I_E_APC_tracked_03_cannon_F",
"B_APC_Tracked_01_rcws_F",
"APC_Wheeled_01_atgm_base_lxWS",
"B_T_APC_Tracked_01_rcws_F",
"B_D_APC_Wheeled_01_atgm_lxWS",
"B_D_APC_Wheeled_01_cannon_lxWS",
"B_D_APC_Wheeled_01_command_lxWS",
"B_ION_APC_Wheeled_01_command_lxWS",
"B_UN_APC_Wheeled_01_command_lxWS",
"B_APC_Wheeled_01_atgm_lxWS",
"B_APC_Wheeled_01_command_lxWS",
"B_T_APC_Wheeled_01_atgm_lxWS",
"B_T_APC_Wheeled_01_command_lxWS",
"RHS_M2A2_wd",
"RHS_M2A2",
"RHS_M2A2_BUSKI_WD",
"RHS_M2A2_BUSKI",
"RHS_M2A3_wd",
"RHS_M2A3",
"RHS_M2A3_BUSKI_wd",
"RHS_M2A3_BUSKI",
"RHS_M2A3_BUSKIII_wd",
"RHS_M2A3_BUSKIII",
"RHS_M6_wd",
"RHS_M6"
];
dapsTrophyHV=[
"O_MBT_04_cannon_F",
"O_MBT_04_command_F",
"O_T_MBT_04_cannon_F",
"O_T_MBT_04_command_F",
"B_MBT_01_arty_F",
"B_MBT_01_cannon_F",
"B_T_MBT_01_cannon_F",
"O_MBT_02_cannon_F",
"O_T_MBT_02_cannon_ghex_F",
"B_APC_Tracked_01_AA_F",
"O_APC_Tracked_02_AA_F",
"B_MBT_01_TUSK_F",
"B_T_MBT_01_TUSK_F",
"rhsusf_m1a1aimwd_usarmy",
"rhsusf_m1a1aimd_usarmy",
"rhsusf_m1a1aim_tuski_wd",
"rhsusf_m1a1aim_tuski_d",
"rhsusf_m1a1fep_wd",
"rhsusf_m1a1fep_d",
"rhsusf_m1a2sep1wd_usarmy",
"rhsusf_m1a2sep1d_usarmy",
"rhsusf_m1a2sep1tuskiwd_usarmy",
"rhsusf_m1a2sep1tuskid_usarmy",
"rhsusf_m1a2sep1tuskiiwd_usarmy",
"rhsusf_m1a2sep1tuskiid_usarmy",
"rhsusf_m1a2sep2wd_usarmy",
"rhsusf_m1a2sep2d_usarmy",
"MEC_IDF_Merkava",
"MEC_IDF_Merkava4",
"WIC_IDF_Merkava",
"WIC_IDF_Merkava4",
"DSF_IDF_Merkava",
"DSF_IDF_Merkava4",
"Burnes_M1A1_MEU_01_Public",
"Burnes_M1A1_MEU_02_Public",
"EUSAD_CE_leopard_2A7",
"EUSAD_DAGUET_leopard_2A7",
"sfp_strv122",
"sfp_strv122b",
"BWA3_Leopard2_Tropen",
"BWA3_Leopard2_Fleck",
"CUP_B_M1A2C_Desert_US_Army","CUP_B_M1A2C_TUSK_Desert_US_Army","CUP_B_M1A2C_TUSK_II_Desert_US_Army",
"CUP_B_M1A2C_OD_US_Army","CUP_B_M1A2C_TUSK_OD_US_Army","CUP_B_M1A2C_TUSK_II_OD_US_Army",
"CUP_B_M1A2C_OD_US_Army","CUP_B_M1A2C_TUSK_OD_US_Army","CUP_B_M1A2C_TUSK_II_OD_US_Army",
"CUP_B_M1A2C_Woodland_US_Army","CUP_B_M1A2C_TUSK_Woodland_US_Army","CUP_B_M1A2C_TUSK_II_Woodland_US_Army"
];
dapsTrophyHVe=[
"West_Abrams"
];
dapsArena=[
"min_rf_t_14",
"min_rf_t_14_desert",
"min_rf_t_14_winter",
"min_rf_t_15",
"min_rf_t_15_desert",
"min_rf_t_15_winter"
];
dapsDrozd=[
"rhs_bmd2m"
];
dapsDrozd2=[
//"O_MBT_02_cannon_F",
//"O_T_MBT_02_cannon_ghex_F"
];
dapsAfganit=[
"rhs_t72be_tv",
"rhs_bmd4ma_vdv",
"rhs_t90am_tv",
"rhs_t90sm_tv",
"rhsgref_cdf_b_t80uk_tv"
//,
//"rhs_t14_tv",
//"rhs_t15_tv"
];
dapsAfganitE=[
"O_SFIA_MBT_02_cannon_lxWS",
"rhs_sprut_vdv"
];
dapsDazzler=[
"CUP_O_T90_RU",
"MEC_SAA_T72",
"MEC_SAA_T90",
"WIC_SAA_T72",
"WIC_SAA_T90",
"rhs_t90a_tv",
"rhs_t90_tv",
"rhs_t80uk",
"CUP_O_BMP3_RU",
"B_MRAP_01_F"
];
dapsIronFist=[
"Burnes_FV4034_01",
"Burnes_FV4034_02"
];
dapsAMAP=["I_MBT_03_cannon_F","I_MBT_03_Cannon_LDF_F"];

dapsVitebsk=[
"O_Heli_Attack_02_dynamicLoadout_F",
"O_Heli_Light_02_dynamicLoadout_F",
"O_Heli_Light_02_unarmed_F",
"O_Plane_CAS_02_dynamicLoadout_F",
"O_T_VTOL_02_infantry_dynamicLoadout_F",
"O_T_VTOL_02_vehicle_dynamicLoadout_F",
"O_SFIA_Heli_Attack_02_dynamicLoadout_lxWS",
"O_Heli_Transport_04_F",
"O_Heli_Transport_04_ammo_F",
"O_Heli_Transport_04_bench_F",
"O_Heli_Transport_04_box_F",
"O_Heli_Transport_04_fuel_F",
"O_Heli_Transport_04_medevac_F",
"O_Heli_Transport_04_repair_F",
"O_Heli_Transport_04_covered_F",
"RHS_Mi24P_vdv",
"RHS_Mi24V_vdv",
"RHS_Mi8T_vdv",
"RHS_Mi8AMT_vdv",
"RHS_Mi8mt_vdv",
"RHS_Mi8mt_Cargo_vdv",
"RHS_Mi8MTV3_vdv",
"RHS_Mi8mtv3_Cargo_vdv",
"RHS_Mi8MTV3_heavy_vdv",
"RHS_Mi8mt_vv",
"RHS_Mi8mt_Cargo_vv",
"RHS_Mi8t_vv",
"RHS_Ka52_vvsc",
"rhs_ka60_c",
"RHS_Mi24P_vvsc",
"RHS_Mi24V_vvsc",
"RHS_Mi24Vt_vvsc",
"rhs_mi28n_vvsc",
"RHS_Mi8AMT_vvsc",
"RHS_Mi8AMTSh_vvsc",
"RHS_Mi8mt_vvsc",
"RHS_Mi8mt_Cargo_vvsc",
"RHS_Mi8MTV3_vvsc",
"RHS_Mi8mtv3_Cargo_vvsc",
"RHS_Mi8MTV3_heavy_vvsc",
"RHS_Mi8T_vvsc",
"RHS_Su25SM_vvsc",
"RHS_Ka52_vvs",
"rhs_ka60_c",
"RHS_Mi24P_vvs",
"RHS_Mi24V_vvs",
"RHS_Mi24Vt_vvs",
"rhs_mi28n_vvs",
"RHS_Mi8AMT_vvs",
"RHS_Mi8AMTSh_vvs",
"RHS_Mi8mt_vvs",
"RHS_Mi8mt_Cargo_vvs",
"RHS_Mi8MTV3_vvs",
"RHS_Mi8mtv3_Cargo_vvs",
"RHS_Mi8MTV3_heavy_vvs",
"RHS_Mi8T_vvs",
"RHS_Su25SM_vvs",
"min_rf_ka_52",
"min_rf_heli_light_black",
"min_rf_heli_light_unarmed_black",
"min_rf_ka_52_grey",
"min_rf_heli_light_grey",
"min_rf_heli_light_unarmed_grey"
];

dapsNemesis=[
"B_Heli_Attack_01_dynamicLoadout_F",
"B_Heli_Transport_01_F",
"B_Heli_Transport_03_F",
"B_Heli_Transport_03_unarmed_F",
"B_CTRG_Heli_Transport_01_sand_F",
"B_CTRG_Heli_Transport_01_tropic_F",
"B_D_Heli_Attack_01_dynamicLoadout_lxWS",
"B_D_Heli_Transport_01_lxWS",
"B_T_VTOL_01_armed_F",
"B_T_VTOL_01_infantry_F",
"B_T_VTOL_01_vehicle_F",
"I_Heli_Transport_02_F",
"I_Heli_light_03_dynamicLoadout_F",
"I_Heli_light_03_unarmed_F",
"I_E_Heli_light_03_dynamicLoadout_F",
"I_E_Heli_light_03_unarmed_F",
"RHS_AH64D",
"RHS_AH64DGrey",
"RHS_AH64D_wd",
"RHS_C130J",
"RHS_C130J_Cargo"
];