if(!dapsAvailable)exitWith{};
private _v=vehicle player;
if(_v==player)exitWith{};
if(((str(findDisplay 312))find"312")>-1)exitWith{};
if!(isNull(getConnectedUAV player))exitWith{};
if(isNil{_v getVariable"dapsType"})exitWith{};
private _crew=FALSE;
if(player==gunner _v)then{_crew=TRUE};
if(player==driver _v)then{_crew=TRUE};
if(player==commander _v)then{_crew=TRUE};
if!(_crew)exitWith{};
private _type=_v getVariable"dapsType";
if(_v getVariable"dapsActive")exitWith{
	_v setVariable["dapsActive",FALSE,TRUE];
	hintSilent format["%1 turned OFF",_type];
	//systemChat format["%1 turned OFF",_type];
	};
_v setVariable["dapsActive",TRUE,TRUE];
hintSilent format["%1 turned ON",_type];
//systemChat format["%1 turned ON",_type];