private _v=_this select 0;
private _i=_this select 1;
private _exit=TRUE;
if((typeOf _i)in dapsExcludedAmmo)exitWith{};
if(_i in dapsDazzled)exitWith{};
dapsDazzled pushBack _i;
if(_i call DAPS_fnc_IsLaserGuided)then{_exit=FALSE};
if(_i call DAPS_fnc_IsIRguided)then{_exit=FALSE};
if(_exit)exitWith{dapsDazzled=dapsDazzled-[_i]};
private _d=_v distance _i;
sleep .2;
if((_v distance _i)>_d)exitWith{dapsDazzled=dapsDazzled-[_i]};
_i setMissileTarget _i;
if!(alive _i)exitWith{};
if(_exit)exitWith{dapsDazzled=dapsDazzled-[_i]};
private _id=getDir _i;
private _rd=[_id,_v]call DAPS_fnc_RelDir2;
[_v,_i,90,.1]spawn DAPS_fnc_MisguideSAM;
[_v,_rd,TRUE]remoteExec["DAPS_fnc_ReportDIRCM"];