name: Build and Release PBO

on:
  push:
    branches:
      - master-altis

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Move source files to 'warlordsredux.altis' subfolder
        run: |
          New-Item -ItemType Directory -Path warlordsredux.altis
          Get-ChildItem -Path $env:GITHUB_WORKSPACE -Exclude warlordsredux.altis | ForEach-Object {
            Move-Item $_.FullName -Destination "$env:GITHUB_WORKSPACE\warlordsredux.altis"
          }

      - name: Download and unzip PBO Manager
        run: |
          Invoke-WebRequest -Uri https://github.com/winseros/pboman3/releases/download/v1.9.1/PBOManager-binaries-1.9.1-200.39e75de.zip -OutFile pbomanager.zip
          Expand-Archive -Path pbomanager.zip -DestinationPath pbomanager

      - name: Clean up unwanted files from warlordsredux.altis
        run: |
          Remove-Item "$env:GITHUB_WORKSPACE\warlordsredux.altis\.git" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item "$env:GITHUB_WORKSPACE\warlordsredux.altis\.github" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item "$env:GITHUB_WORKSPACE\warlordsredux.altis\.gitmodules" -Force -ErrorAction SilentlyContinue
          Remove-Item "$env:GITHUB_WORKSPACE\warlordsredux.altis\.gitattributes" -Force -ErrorAction SilentlyContinue
          Remove-Item "$env:GITHUB_WORKSPACE\warlordsredux.altis\.gitattributes" -Force -ErrorAction SilentlyContinue

      - name: Build PBO from warlordsredux.altis
        run: |
          $pboc = "$env:GITHUB_WORKSPACE\pbomanager\PBO Manager\pboc.exe"
          & $pboc pack "$env:GITHUB_WORKSPACE\warlordsredux.altis" --output-directory "$env:GITHUB_WORKSPACE"

      - name: Upload PBO to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packed-pbo
          path: '*.pbo'
